default: &default
  adapter: postgresql
  timeout: 5000
  database: app_development
  pool: 5
  host: db
  port: 5432
  username: postgres
  password: <%= ENV["DB_ENV_POSTGRES_PASSWORD"] %>
  encoding: unicode

development:
  <<: *default

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  timeout: 5000
