default: &default
  adapter: postgresql
  timeout: 5000
  database: mix8_development
  pool: 5
  host: localhost
  port: 5432
  username: mix8
  password: <%= ENV["DB_ENV_POSTGRES_PASSWORD"] %>
  encoding: unicode

development:
  <<: *default

test:
  <<: *default
  database: mix8_test

production:
  <<: *default
  database: mix8_production
  timeout: 5000
