# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c006fdb9de80daa6e3bbf234b19fb8a738f401a58a5bbb7201da0f593f9fd861adae49667f11b56ddedf0ee1759721d2e1fdc20a3d05c35759ab28c6c35ba0c5
  host_url: http://mix8.dev:3000
  api_host_url: http://api.mix8.dev:3000
  rackspace_username: oleg8stem
  rackspace_api_key: 1ff56d6cd92b4e568c21048c1ed965bb
  rackspace_temp_url_key: aYiPUlQdj0
  rackspace_images_asset_host: http://b60e3e72039a41b0ed6e-b0721e024cdcf8f191f91075bb688ea5.r77.cf5.rackcdn.com
  rackspace_audio_asset_host: http://675f6fd46a1ebb9ed57a-8a8f39f3c89338df47f97bf18e6a7c7b.r31.cf5.rackcdn.com
  facebook_key: 1513797368918406
  facebook_secret: a6e1b5eccf3d7a96cb702dd92e71649f
  sendgrid_username: 8Stem
  sendgrid_password: 911PikeSt

test:
  secret_key_base: 19f8f482f8e8b71eae00d967b15f22a4eb92611158a2857b309f62a974c431b57a74ca70701e763c692d32ec2ae320f02dd15232f731803199c422ba9d92d312


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
